build:
  image: mono:latest
  commands:
    - nuget restore
    - xbuild /p:Configuration="NoUnitTest"

publish:
  sftp:
    host: 192.168.1.51
    port: 22701
    username: artifacts
    password: artifacts
    destination_path: /data/mask-dotnet-client
    files:
      - MaskNetworkDLL/bin/NoUnitTest/*.dll