version: 0.1.{build}

configuration: Release

before_build:
  - nuget restore

build:
  parallel: true                  # enable MSBuild parallel builds
  project: MaskGame.sln      # path to Visual Studio solution or project
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
  verbosity: normal